### PR TITLE
initalize backend

### PR DESCRIPTION
**Pull request by coderJakub**
### Scope:
Using RestAPI I created a Django backend. VMs can be created, deleted and changed using post, get and delete request.

### Start Backend:
To run the Python VM you may need permission to execute shell scripts (just for Windows :D):
`Set-ExecutionPolicy RemoteSigned -Scope Process`

_Starting the VM:_
`.\env\Scripts\activate`

_Start backend:_
`python manage.py runserver`

API can be found at: _http://127.0.0.1:8000/api/VM/_

### Use of the API:
Under _http://127.0.0.1:8000/api/VM/_ you can view the VMs (GET) and add a new VM (POST). If you enter an existing DNS name, the existing VM will be edited.
Under _http://127.0.0.1:8000/api/VM/"id"_  you can view the VM with the ID and delete it with a DELETE request.

### CODE REVIEW

**Comment by coderJakub** [comment]
tbd: Using a PostgreSQL database instead of the SQLite database provided by django

**Review by henrikalbrecht — CHANGES_REQUESTED** [review]
1. The first command you provide is a Windows command. That has atleast to be mentioned. It would be even better if you use the provided docker container because it makes it easier for everybody to recreate the functionality. Furthermore it would erase the need of an VM .(Not 100% sure though :D) 
2. Kinda refers to point 1. If you don´t use a VM / Dockercontainer everybody knows it would be good to say which dependencies the backend has. I had no trouble recreating it inside the docker container because it had all the tools installed. 
3. The second last key in the JSON is called ip and is configured as an integer. What ip is being used as integer? What am I missing? ;D
4. There is a small typo `opertation_sys`.

Besides those points iI really like the prototype. Having the check if a value is formatted in the right way (email, has to be in email format etc.) is great. Furthermore I also used the Django Rest Framework and the same approach when I was teaching Django myself.  So all in All I do really like it.

Just on last question. The commit is 7000+ files big. Does Django have something like a build folder or something? So that we can ignore those files in the .gitignore and they are being build when the server is being started?

**Comment by coderJakub** [comment]
I talked to Paul and we decided to first use the VM provided by Python for the prototype (#57). I can also outsource the whole thing to Docker if it's needed. The many files were created because of the VM; Django only has around 15.

**Comment by don-ny** [comment]
> I talked to Paul and we decided to first use the VM provided by Python for the prototype (#57). I can also outsource the whole thing to Docker if it's needed. The many files were created because of the VM; Django only has around 15.

@henrikalbrecht  Jup, PO mentioned, that to demonstrate the vertical function it is not necessary to run everything in docker containers.

@coderJakub 
First off: Nice work - thank you! :-)
### 1) configuration/running server:
I needed to do some additional install on my PC for the prerequesites. This is what I've done to make it run and it should work the same for everybody.
- install latest python3 version (check option to include in PATH variable during install!)
- open Windows command prompt
- navigate to src\prototype\backend\ folder
- execute .\env\scripts\activate to enter python venv
- pip install django djangorestframework
- python manage.py runserver

**Please add this "guide" to our Wiki**

### 2) database fields:
- add "Vergabe-Status":
Please include the "Vergabe-Status" that represents at which provisioning state a VM is (unassigned, in preparation, in use).
If you need a bit more info on this, check out the wireframe diagram for Use Case 01.
(use a better name than "Vergabe-Status" for the field :D)
- rename "intern_net":
Please rename "intern_net" to "external_net". 
The default is to have a VM in the internal HTW net. 
Looking into the future, the default value in our database should be "false" so DB transaction is only needed when PO checks the field for "external network". (this is rather a "good practice" thing)

**Comment by henrikalbrecht** [comment]
1. I know that the PO said that not everything has to run in an individual docker container. Using one for developing makes everything easier though, since we can skip that whole configuration/running  server: part because the docker container has everything setup. Its just time efficient. Furthermore this is not completely dealing with the problems the devs had with different working environments. using the docker container gives everyone the same environment. (I just did it with arshnoor its easy) 

2. I like those suggestions. :)
3. I had the same though. But using zip files completely kills the version control aspect since you dont see what has been changed. Therefore i dont think its a good idea. ( I have also never seen it anywhere)

I am going to make new issues for your suggestions but have to merge the branch now so arshnoor can start working on the frontend. I think we should debate about the VM/ docker topic on monday

**Review by henrikalbrecht — APPROVED** [review]

**Pull request merged**
